import { AfterViewInit, ElementRef, EventEmitter, Renderer2, NgZone, OnDestroy, OnInit } from '@angular/core';
import 'rxjs/add/observable/zip';
import 'rxjs/add/observable/fromEvent';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/pairwise';
import 'rxjs/add/operator/startWith';
import 'rxjs/add/operator/takeWhile';
import 'rxjs/add/operator/skipWhile';
import 'rxjs/add/operator/debounceTime';
export declare class NgxInfiniteScrollDirective implements AfterViewInit, OnInit, OnDestroy {
    private el;
    private renderer;
    private zone;
    scrollbarAnimationInterval: number;
    scrollDebounceTimeAfterDOMMutation: number;
    scrollUpPercentilePositionTrigger: number;
    onScrollUp: EventEmitter<null>;
    private scrollChanged;
    private readonly scrollPositionChanged;
    private readonly scrollDownChanged;
    private readonly scrollUpChanged;
    private readonly scrollRequestZoneEntered;
    private readonly requestDispatcher;
    private previousScrollTop;
    private previousScrollHeight;
    private domMutationObserver;
    private domMutationEmitter;
    private scrollStreamActive;
    private initMode;
    constructor(el: ElementRef, renderer: Renderer2, zone: NgZone);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    scrollTo(scrollTop?: number): void;
    private registerScrollEventHandler();
    private registerMutationObserver();
    private registerInitialScrollPostionHandler();
    private registerRequestScrollPositionHandler();
    private registerRequestDispatcher();
}
